// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMS;

#nullable disable

namespace SMS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230329044954_sample3")]
    partial class sample3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("SMS.SelecStudent", b =>
                {
                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Idx");

                    b.ToTable("SelectedStudent");
                });

            modelBuilder.Entity("SMS.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("GPA")
                        .HasColumnType("REAL");

                    b.Property<char>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelecStudentIdx")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SelecStudentIdx");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SMS.Student", b =>
                {
                    b.HasOne("SMS.SelecStudent", null)
                        .WithMany("Studs")
                        .HasForeignKey("SelecStudentIdx");
                });

            modelBuilder.Entity("SMS.SelecStudent", b =>
                {
                    b.Navigation("Studs");
                });
#pragma warning restore 612, 618
        }
    }
}
